baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Planned Reactor Content'
minify = true
publishDir = '../generated'
cleanDestinationDir = true
disableKinds = ['home','sitemap','taxonomy']
ignoreErrors = ["error-disable-taxonomy"]