# When a markdown file is changed automatically generate a Pull Request with the updated HTML files
name: "Generate HTML"
on:
  # Used for manually triggering jobs
  push:
    branches:
    - main
    paths:
    - "planning"
    - "**.md"

jobs:
  html-generation:
    runs-on: ubuntu-latest
    name: Generate HTML Files
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.88.0'
    - name: Generate Files
      run: |
        rm -rf generated
        hugo --minify -s planning -d ../generated
    # Open PR and submit modified pages
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update HTML Files
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: automated-html-update
        delete-branch: true
        title: '[Automated] Update HTML Files'
        labels: "automation"
        body: |
          Updates session HTML content
          
          Auto-generated by [create-pull-request][1]
          [1]: https://github.com/peter-evans/create-pull-request
        assignees: runewake2
        reviewers: runewake2
        draft: false